import type { Deal } from "@/types/deal";

export const mockDeals: Deal[] = [
  {
    id: "deal-001",
    productName: "20V MAX XR Brushless Impact Driver Kit",
    brand: "DEWALT",
    retailer: "Home Depot",
    storeName: "Lake Mary #0279",
    city: "Lake Mary",
    state: "FL",
    distanceMiles: 5.8,
    retailPrice: 179,
    clearancePrice: 49,
    resalePrice: 119,
    estimatedProfit: 47,
    roi: 95.9,
    inventory: 6,
    buyScore: 94,
    status: "strong-buy",
    category: "Tools",
    updatedMinutesAgo: 8,
  },
  {
    id: "deal-002",
    productName: "M18 REDLITHIUM XC 5.0Ah Battery",
    brand: "Milwaukee",
    retailer: "Lowe's",
    storeName: "Sanford #1641",
    city: "Sanford",
    state: "FL",
    distanceMiles: 9.2,
    retailPrice: 149,
    clearancePrice: 39,
    resalePrice: 94,
    estimatedProfit: 36,
    roi: 92.3,
    inventory: 4,
    buyScore: 89,
    status: "buy",
    category: "Tools",
    updatedMinutesAgo: 12,
  },
  {
    id: "deal-003",
    productName: '27" QHD Gaming Monitor 165Hz',
    brand: "LG",
    retailer: "Walmart",
    storeName: "Sanford Supercenter #857",
    city: "Sanford",
    state: "FL",
    distanceMiles: 7.4,
    retailPrice: 249,
    clearancePrice: 119,
    resalePrice: 199,
    estimatedProfit: 42,
    roi: 35.3,
    inventory: 3,
    buyScore: 78,
    status: "maybe",
    category: "Electronics",
    updatedMinutesAgo: 21,
  },
  {
    id: "deal-004",
    productName: "Cordless Stick Vacuum",
    brand: "Shark",
    retailer: "Target",
    storeName: "Lake Mary",
    city: "Lake Mary",
    state: "FL",
    distanceMiles: 3.6,
    retailPrice: 299,
    clearancePrice: 104.99,
    resalePrice: 184,
    estimatedProfit: 34,
    roi: 32.4,
    inventory: 2,
    buyScore: 72,
    status: "maybe",
    category: "Home",
    updatedMinutesAgo: 34,
  },
  {
    id: "deal-005",
    productName: "12V MAX 2-Tool Combo Kit",
    brand: "Bosch",
    retailer: "Lowe's",
    storeName: "Altamonte Springs #0604",
    city: "Altamonte Springs",
    state: "FL",
    distanceMiles: 12.1,
    retailPrice: 159,
    clearancePrice: 35,
    resalePrice: 98,
    estimatedProfit: 43,
    roi: 122.9,
    inventory: 8,
    buyScore: 96,
    status: "strong-buy",
    category: "Tools",
    updatedMinutesAgo: 5,
  },
  {
    id: "deal-006",
    productName: "Smart Wi-Fi Air Fryer Pro",
    brand: "Cosori",
    retailer: "Walmart",
    storeName: "Casselberry Supercenter #943",
    city: "Casselberry",
    state: "FL",
    distanceMiles: 14.7,
    retailPrice: 129,
    clearancePrice: 49,
    resalePrice: 79,
    estimatedProfit: 12,
    roi: 24.5,
    inventory: 7,
    buyScore: 58,
    status: "skip",
    category: "Kitchen",
    updatedMinutesAgo: 19,
  },
];

export const categories = ["All categories", "Tools", "Electronics", "Home", "Kitchen"];
export const retailers = ["All stores", "Home Depot", "Lowe's", "Walmart", "Target"];
